version: '3.3'
networks: {rasa-network: {}}
services:
  rasa:
    image: ki-campus:1.0
    ports:
      - "12345:5005"
    command:  run -vv -m /app/models/ --enable-api --endpoints /app/endpoints.yml --credentials /app/credentials.yml --cors "*"
    networks: ['rasa-network']
    depends_on:
      - duckling
  duckling:
    image: rasa/duckling:latest
    ports:
      - "8000:8000"
    networks: ['rasa-network']